{% set name = "botcity-maestro-sdk" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bed54b3e72799e284776bdd5e1601d7a6bf9dd4cdef54623a798945f881c8cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests

test:
  imports:
    - botcity.maestro

about:
  home: https://github.com/botcity-dev/botcity-maestro-sdk-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BotCity Maestro SDK - Python
  description: |
    BotMaestro is an automation platform to facilitate the development,
    deploy and orchestration of automation robots. This package provides
    a Python interface to this service.
  doc_url: https://botcity-dev.github.io/botcity-maestro-sdk-python
  dev_url: https://github.com/botcity-dev/botcity-maestro-sdk-python

extra:
  recipe-maintainers:
    - hhslepicka
