{% set name = "botcity-maestro-sdk" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa4860cab5ba508d97ce83a34638bd1f0096faeb63b5806b8a7a451285e95876

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - distro
    - importlib-metadata
    - packaging
    - requests
    - requests-toolbelt

test:
  requires:
    - python {{ python_min }}
  imports:
    - botcity.maestro

about:
  home: https://github.com/botcity-dev/botcity-maestro-sdk-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BotCity Maestro SDK - Python
  description: |
    BotMaestro is an automation platform to facilitate the development,
    deploy and orchestration of automation robots. This package provides
    a Python interface to this service.
  doc_url: https://botcity-dev.github.io/botcity-maestro-sdk-python
  dev_url: https://github.com/botcity-dev/botcity-maestro-sdk-python

extra:
  recipe-maintainers:
    - hhslepicka
